version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/usr/src/main/
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - MODE=server
      - SQL_HOST=host.docker.internal
      - REDIS_DB_HOST=host.docker.internal

    restart: unless-stopped

  celery_worker:
    build: .
    # command: celery -A main worker --loglevel=info
    volumes:
      - .:/usr/src/main/
    env_file:
      - .env
    environment:
      - MODE=celery_worker
      - SQL_HOST=host.docker.internal
      - REDIS_DB_HOST=host.docker.internal
    depends_on:
      - web

  celery_beat:
    build: .
    # command: celery -A main beat --loglevel=info
    volumes:
      - .:/usr/src/main/
    env_file:
      - .env
    environment:
      - MODE=celery_beat
      - SQL_HOST=host.docker.internal
      - REDIS_DB_HOST=host.docker.internal
    depends_on:
      - web
