version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/usr/src/main/
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - MODE=server
    restart: unless-stopped

  celery_worker:
    build: .
    # command: celery -A main worker --loglevel=info
    volumes:
      - .:/usr/src/main/
    env_file:
      - .env
    environment:
      - MODE=celery_worker
    depends_on:
      - web

  celery_beat:
    build: .
    # command: celery -A main beat --loglevel=info
    volumes:
      - .:/usr/src/main/
    env_file:
      - .env
    environment:
      - MODE=celery_beat
    depends_on:
      - web
