version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - MODE=server
      - SQL_HOST=host.docker.internal
      - REDIS_DB_HOST=host.docker.internal
      - PORT=8000
      - BASE_URL=http://localhost:8000

    restart: unless-stopped

  celery-worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A main worker --loglevel=info
    env_file:
      - .env
    environment:
      - MODE=celery_worker
      - SQL_HOST=host.docker.internal
      - REDIS_DB_HOST=host.docker.internal
      - PORT=8000
      - BASE_URL=http://localhost:8000
    depends_on:
      - backend
    # deploy:
    #   # replicas: 2
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: 50M
    #     reservations:
    #       cpus: '0.25'
    #       memory: 20M
    restart: unless-stopped

  celery-beat:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A main beat --loglevel=info
    env_file:
      - .env
    environment:
      - MODE=celery_beat
      - SQL_HOST=host.docker.internal
      - REDIS_DB_HOST=host.docker.internal
      - PORT=8000
      - BASE_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
    
  # gen_ai_app:
  #   build: 
  #     context: .
  #     dockerfile: ./dockerfiles/Dockerfile.genai
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 80
  #   ports:
  #     - 8080:80
