version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    volumes:
      - .:/usr/src/main/
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - MODE=server
      - SQL_HOST=host.docker.internal
      - REDIS_DB_HOST=host.docker.internal
      - PORT=8000
      - BASE_URL="http://localhost:8000"

    restart: unless-stopped

  celery_worker:
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    # command: celery -A main worker --loglevel=info
    volumes:
      - .:/usr/src/main/
    env_file:
      - .env
    environment:
      - MODE=celery_worker
      - SQL_HOST=host.docker.internal
      - REDIS_DB_HOST=host.docker.internal
      - PORT=8000
      - BASE_URL="http://localhost:8000"
    depends_on:
      - backend

  celery_beat:
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    # command: celery -A main beat --loglevel=info
    volumes:
      - .:/usr/src/main/
    env_file:
      - .env
    environment:
      - MODE=celery_beat
      - SQL_HOST=host.docker.internal
      - REDIS_DB_HOST=host.docker.internal
      - PORT=8000
      - BASE_URL="http://localhost:8000"
    depends_on:
      - backend

  # gen_ai_app:
  #   build: 
  #     context: .
  #     dockerfile: ./dockerfiles/Dockerfile.genai
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 80
  #   ports:
  #     - 8080:80
