EXCLUDE_WEBSITES = [
    "www.digitaljournal.com",
    # "www.cxotoday.com",
    # "www.argylereport.com",
    # "www.sci.news",
    # "spectrum.ieee.org"
]

ALLOWED_SEARCH_KEYS = {
    "Headline Highlight": [
        "Databases",
        "Low-Code/No-Code Platforms",
        "Quantum Computing Software",
        "Neural Network Architectures",
        "MLOps",
        "Federated Learning",
        "Edge Computing Software",
        "Rust Programming",
        "WebAssembly (Wasm)",
        "Serverless Architectures",
        "Progressive Web Apps (PWAs)",
        "Blockchain and Decentralized Applications (dApps)",
        "API-First Development",
        "Micro Frontends",
        "Homomorphic Encryption",
    ],
    "Trending Tech": [
        "AI & Machine Learning",
        "Wearable Technology",
        "Blockchain & Cryptocurrency",
        "Quantum Computing",
        "Internet of Things (IoT)",
        "Space Tech & Exploration",
        "Augmented Reality (AR) & Virtual Reality (VR)",
        "5G & Connectivity",
        "Green Tech",
        "Autonomous Vehicles",
    ],
    "Software Scoop": [
        "Language Evolution",
        "Development Frameworks & Libraries",
        "Best Practices",
        "Open-Source Ecosystem",
        "Development Tools & IDEs",
        "Database Dive",
        "Microservices & Architecture",
        "Augmented Reality (AR) and Virtual Reality (VR) Software Development",
        "Continuous Intelligence (CI)",
        "Graph Databases and GraphQL",
        "Post-Quantum Cryptography",
        "Sustainable Software Engineering",
        "Human Augmentation Software",
    ],
}

ALLOWED_AUTOMATION_TIP_OF_THE_DAY = {
    "Script Regular Tasks": "Use scripting languages like Python or Bash to automate daily mundane tasks.",
    "Email Sorting": "Use email rules to automatically sort and label your incoming mail.",
    "Automate Reports": "Use tools like PowerBI or Tableau to automate your reporting processes.",
    "Keyboard Shortcuts": "Learn keyboard shortcuts for your most-used applications to save time.",
    "Browser Automation": "Explore tools like Selenium for repetitive browser tasks.",
    "Cron Jobs": "Schedule tasks to run automatically at specified intervals using Cron on Unix-based systems.",
    "Task Schedulers": "On Windows? Use Task Scheduler to run scripts at specified times.",
    "Use IFTTT": "Connect different apps and devices together for automated workflows.",
    "Auto-Backup": "Always have an automated backup solution in place for critical data.",
    "APIs": "Integrate with APIs to pull or push data automatically between systems.",
    "Database Jobs": "Schedule regular database jobs to clean and manage your data.",
    "Use Zapier": "Create workflows that connect your favorite apps and automate tasks.",
    "Automate Social Posts": "Tools like Buffer or Hootsuite can help schedule and automate social media posts.",
    "Spreadsheet Macros": "Use macros in Excel to automate repetitive tasks.",
    "Automate Software Updates": "Ensure your software is always up-to-date automatically.",
    "Password Managers": "Use them to automate and streamline your login processes.",
    "Cloud Sync": "Automate the syncing of your files across devices using cloud services.",
    "Regular Cleanup": "Schedule regular automated cleanup scripts for your computer.",
    "Auto-responders": "Use them for emails when you're out of office or too busy.",
    "Automate Testing": "Implement continuous integration (CI) tools to automate software testing.",
    "Auto-Billing": "Set up automatic payments for recurring bills.",
    "Chatbots": "Use them on websites for automated customer support.",
    "Automate Onboarding": "Use tools to automatically onboard new employees or users.",
    "Use Virtual Assistants": "Tools like Siri, Alexa, or Google Assistant can automate many tasks.",
    "Auto-archives": "Set old files or emails to archive automatically.",
    "Data Scraping": "Automate data collection from the web using tools like Scrapy.",
    "Automate Data Entry": "Use Optical Character Recognition (OCR) tools.",
    "Auto Notifications": "Set up triggers to get automated alerts for important events.",
    "Automate File Naming": "Use scripts to batch rename files.",
    "Sync Calendars": "Automatically sync your work and personal calendars.",
    "Automate Image Editing": "Use batch processing in tools like Photoshop.",
    "Automate Video Editing": "Explore tools that allow batch video processing.",
    "Cloud Functions": "Use AWS Lambda or Google Cloud Functions to run code without provisioning servers.",
    "Mobile Automation": "Tools like Appium can help automate mobile tasks.",
    "Automate Data Validation": "Regularly check data integrity automatically.",
    "Automate Security Checks": "Schedule regular automated security scans.",
    "Auto Logout": "Set devices to log out automatically after inactivity for security.",
    "Automate Analytics": "Use Google Analytics or similar tools to get regular automated reports.",
    "AI Predictions": "Use machine learning to automate predictions and decisions.",
    "Auto-investing": "Set up automated investment contributions.",
    "Automate Ad Campaigns": "Adjust your online ad spend automatically based on results.",
    "Automate Customer Feedback": "Use automated surveys post-purchase or post-interaction.",
    "Auto Renewals": "Set up domains, SSL certificates, and other online services to renew automatically.",
    "Automate Database Backups": "Always have recent backups by automating the process.",
    "Automate Code Formatting": "Use tools like Prettier or Black for consistent code styles.",
    "Automate Documentation": "Tools like Doxygen can help generate code documentation.",
    "Server Monitoring": "Set up tools like Nagios to automatically monitor server health.",
    "Automate Disk Cleanup": "Schedule regular disk cleanups on servers.",
    "Auto Scaling": "Set your servers to scale up or down automatically based on traffic.",
    "Automate Transcriptions": "Use services to automatically transcribe meetings.",
    "Automate Meeting Scheduling": "Tools like Calendly can help.",
    "Auto File Organization": "Use scripts to sort and move files based on rules.",
    "Automate Invoicing": "Use business software to send invoices automatically.",
    "Automate Follow-ups": "Set CRM tools to remind or send follow-up messages.",
    "Auto Data Sync": "Synchronize data between different platforms automatically.",
    "Automate Affiliate Marketing": "Use tools to track and manage commissions automatically.",
    "Automate VM Snapshots": "If you use virtual machines, schedule regular snapshots.",
    "Automate Mobile Device Management": "Tools like MDM can push updates and configurations.",
    "Auto Screen Breaks": "Use tools to remind you to take breaks after periods of screen time.",
    "Automate SEO Audits": "Schedule regular SEO checks for your website.",
    "Auto Data Encryption": "Ensure data is automatically encrypted when stored.",
    "Automate Network Scans": "Regularly check for vulnerabilities in your network.",
    "Automate Compliance Checks": "For industries with regulations, automate compliance verifications.",
    "Auto Expense Tracking": "Use apps that link to accounts and track expenses automatically.",
    "Automate VM Deployments": "Use Docker or Kubernetes for automated container management.",
    "Automate Code Reviews": "Use tools that automatically review and suggest code improvements.",
    "Automate Cloud Resource Monitoring": "Keep an eye on cloud costs and usage with automated tools.",
    "Auto Debugging": "Implement tools that automatically detect",
}

FUN_FACTS = {
    "The Bug": 'The term "bug" in software development originated when a real moth was found in a computer relay in 1947.',
    "Domain Deal": 'The most expensive domain ever purchased was "CarInsurance.com" for $49.7 million in 2010.',
    "Bitcoin Pizzas": "The first real-world transaction using Bitcoin bought two pizzas for 10,000 bitcoins.",
    "AI Art": "There's an AI that transforms your doodles into stunning artworks.",
    "ENIAC": "The first digital computer, ENIAC, weighed over 27 tons and took up 1800 square feet.",
    "Y2K Bug": 'The "Y2K bug" made many believe that planes might fall out of the sky at the millennium\'s turn.',
    "Hello, Siri": "Apple's Siri voice assistant has its origins in a project originally developed by the U.S. Defense Department.",
    "Ephemeral Snaps": "Over 3 billion snaps are sent on Snapchat daily.",
    "Turing's Chess": "Alan Turing developed the first ever chess program even before computers could play it.",
    "First Video Game": 'The first video game patent ever filed was for a game called "Tennis for Two" in 1947.',
    "Tech Predictions": 'In 1943, IBM\u2019s chairman said, "I think there is a world market for maybe five computers."',
    "Google's Data": "Google processes over 40,000 search queries every second, totaling over 3.5 billion searches a day.",
    "QWERTY Origins": "The QWERTY keyboard layout was designed to prevent typewriter jamming.",
    "Meme Origin": 'The term "meme" was first coined by Richard Dawkins in his 1976 book "The Selfish Gene."',
    "Viral Cats": "Nearly 15% of all internet traffic is made up of cat videos.",
    "HDD Space": "The first hard drive ever made was in 1956 and was 5 MB in size.",
    "Shortest Code": "The shortest valid C++ program is int main;.",
    "OpenAI's GPT": "OpenAI's GPT-3 model, one of the world's most powerful language models, has 175 billion parameters.",
    "Python's Name": 'The programming language Python is not named after the snake, but the comedy show "Monty Python\'s Flying Circus."',
    "Oldest Website": "The oldest still-functioning website is CERN's original World Wide Web page, dating back to 1991.",
    "Robot Citizenship": "In 2017, a robot named Sophia was given citizenship in Saudi Arabia.",
    "Game Sales": "The best-selling video game of all time is Minecraft, with over 200 million copies sold.",
    "First Email": 'The "@" symbol was used in the very first email ever sent, by Ray Tomlinson in 1971.',
    "First Computer Virus": 'The first computer virus was named "Brain" and was detected in the 1980s.',
    "Nintendo Age": "Nintendo was founded in 1889 and initially produced playing cards.",
    "CAPTCHA Meaning": 'CAPTCHA stands for "Completely Automated Public Turing test to tell Computers and Humans Apart."',
    "Wi-Fi Origins": "Wi-Fi doesn't stand for anything. It's not short for \"Wireless Fidelity\" or anything else.",
    "First Domain": 'The first-ever domain name registered was "Symbolics.com" in 1985.',
    "Amazon's Name": 'Amazon was initially called "Cadabra" but was changed because it sounded too much like "cadaver."',
    "Algorithm Origins": 'The word "algorithm" comes from the name of the mathematician Al-Khwarizmi.',
    "Gaming Pioneers": "Women have been involved in video game development since the 1970s.",
    "WWW Languages": "The World Wide Web was originally developed in the French research facility CERN.",
    "AI Music": "AI has been used to compose entire albums of music.",
    "Emoji Language": "There are over 3,000 officially recognized emojis.",
    "Virtual Reality": "The concept of VR was introduced as early as the 1860s, long before modern VR technology.",
    "Robot Pets": "Sony introduced a robot dog named AIBO in 1999, which could learn and express itself.",
    "Ancient Calculator": 'The ancient Greek "Antikythera mechanism" is often considered the world\'s first analog computer.',
    "Silicon Beginnings": "Silicon Valley got its name from the silicon used in computer chips.",
    "Billionaire Tweet": "Elon Musk once added $1.3 billion to his net worth with a single tweet.",
    "Flying Internet": "Google's Project Loon aims to provide internet access via balloons floating in the stratosphere.",
    "Twitter's Origin": 'Twitter was originally called "twttr," inspired by Flickr.',
    "Mobile Revolution": "More people in the world have access to mobile phones than toilets.",
    "Deep Blue": "In 1997, IBM's Deep Blue became the first computer to beat a reigning world chess champion.",
    "Virtual Popstars": "Hatsune Miku, a virtual pop star from Japan, sells out concerts worldwide.",
    "E-Sports Growth": "Competitive gaming, or e-sports, is projected to surpass $1.5 billion in revenue by 2023.",
    "AI Screenplays": 'An AI wrote a screenplay for a short film called "Sunspring" in 2016.',
    "CD Capacity": "The size of a CD was determined by the length of Beethoven's 9th Symphony, aiming for 74 minutes.",
    "Blu-Ray Color": "Blu-Ray discs are named for the blue laser used to read them.",
    "Radio Waves in Space": "Old TV broadcasts are still traveling outward through space and could potentially be picked up by distant civilizations.",
    "Early E-Book": "The first e-book ever created was a digital version of the Declaration of Independence in 1971.",
    "Internet Devices": "There are more devices connected to the internet than there are people on Earth.",
    "Space Internet": 'NASA has developed an "Internet for space," allowing for better data communication between Earth and rovers on Mars.',
    "First Mobile Phone": "The first mobile phone call was made in 1973 by Martin Cooper.",
    "Morse Code Text": 'The first text message ever sent was "Merry Christmas" in 1992.',
    "Dynamic Duo": "The creators of the Python programming language and the Java programming language knew each other.",
    "First Webcam": "The world's first webcam was used at Cambridge University to monitor a coffee pot.",
    "Binary Language": "The Yuki tribe in California used a binary system of drums to send messages over long distances.",
    "AI News": "China's state news agency has an AI anchor presenting some of its news.",
    "Early Storage": "One gigabyte of storage in 1981 would have cost around $300,000.",
    "Apple's Logo": "Apple's original logo featured Sir Isaac Newton sitting under an apple tree.",
    "Video Game Olympics": "Esports will be a medal event in the 2022 Asian Games.",
    "Tech Oscars": "The Academy Awards offers Oscars for technological achievements.",
    "Viral Boom": '"Gangnam Style" was so popular it broke YouTube\'s view counter, requiring an upgrade.',
    "Flexible Phones": "The world's first flexible phone was showcased in 2008.",
    "Robot Rights": 'A robot named "Sophia" is the first robot to receive citizenship and rights.',
    "Distant Internet": "There's a plan to provide internet on the Moon by 2022.",
    "Light Speed": "Quantum computers work by placing data in a state where it is both 0 and 1 simultaneously.",
    "Code from Space": "Astronauts onboard the International Space Station coded a program, making it the first coding done in space.",
    "Gaming Science": "Playing video games can improve memory, reduce stress, and enhance cognitive skills.",
    "Wearable Tech": "The first wearable tech device was a 17th-century Chinese abacus ring.",
    "Wi-Fi History": "Wi-Fi technology is a result of a failed experiment trying to detect black holes.",
    "Quantum Internet": "Scientists are working on a quantum internet that will be theoretically hack-proof.",
    "Virtual Plants": "There's an AI that can predict the future growth of plants.",
    "Digital Smell": "Scientists are developing technology to transmit smell over the internet.",
    "Longest Uptime": "The record for the longest server uptime (time without a restart) was over 16 years.",
    "Data Storage": "It's estimated that by 2040, the world will run out of computer storage.",
    "Tech Tattoos": "There are tattoos being developed that can be used as biometric authentications.",
    "Self-Healing Tech": 'Scientists are developing materials that can "heal" themselves when damaged.',
    "Human-Powered Tech": "There's a tech that can charge your phone using the heat from your body.",
    "Robotic Chef": "The world's first robot kitchen chef was showcased in 2015.",
    "First PC Virus": "The first PC virus was released in 1986 and was called (c)Brain.",
    "Coding Languages": "There are over 700 programming languages in the world.",
    "Quantum Entanglement": 'This phenomenon was described by Einstein as "spooky action at a distance."',
    "Internet Population": "Over half of the world's population now uses the internet.",
    "Digital Detox": 'There are "detox" retreats specifically for people addicted to technology.',
    "3D Printed Organs": "Scientists are in the process of 3D printing organs for transplants.",
    "Digital Twins": 'There\'s technology that can create a "digital twin" of cities to simulate various scenarios.',
    "Tech Music": "The algorithmic music genre involves compositions created using algorithms.",
    "Nano-Tech": "There's nanotechnology being developed that can purify water in seconds.",
    "Smart Tattoos": "Tattoos are being developed that change color based on changes in your biochemistry.",
    "Code Legacy": "Ancient civilizations like the Incas used a form of coding with knotted strings called Quipus.",
    "Light-based Computing": "Scientists are working on computers that use light instead of electricity.",
    "Bio Computers": "Computers are being developed using DNA and organic processes.",
    "AI Ethics": "There are philosophers working on the morality and ethics of artificial intelligence.",
    "Space Music": "There's a record with music and sounds from Earth aboard the Voyager spacecraft for aliens to find.",
    "Tech in Fiction": 'Jules Verne\'s "From the Earth to the Moon" predicted weightlessness in space travel before we ever went to space.',
    "Silent Tech": "There's technology that can mute city noise without windows being closed.",
    "AI Dreams": 'There\'s an AI developed by Google called DeepDream, which "dreams" and creates psychedelic images.',
    "Invisible Tech": "Scientists are developing materials for technology that can render objects invisible.",
}

BOLD_CHARS = {
    "a": "𝗮",
    "b": "𝗯",
    "c": "𝗰",
    "d": "𝗱",
    "e": "𝗲",
    "f": "𝗳",
    "g": "𝗴",
    "h": "𝗵",
    "i": "𝗶",
    "j": "𝗷",
    "k": "𝗸",
    "l": "𝗹",
    "m": "𝗺",
    "n": "𝗻",
    "o": "𝗼",
    "p": "𝗽",
    "q": "𝗾",
    "r": "𝗿",
    "s": "𝘀",
    "t": "𝘁",
    "u": "𝘂",
    "v": "𝘃",
    "w": "𝘄",
    "x": "𝘅",
    "y": "𝘆",
    "z": "𝘇",
    "A": "𝗔",
    "B": "𝗕",
    "C": "𝗖",
    "D": "𝗗",
    "E": "𝗘",
    "F": "𝗙",
    "G": "𝗚",
    "H": "𝗛",
    "I": "𝗜",
    "J": "𝗝",
    "K": "𝗞",
    "L": "𝗟",
    "M": "𝗠",
    "N": "𝗡",
    "O": "𝗢",
    "P": "𝗣",
    "Q": "𝗤",
    "R": "𝗥",
    "S": "𝗦",
    "T": "𝗧",
    "U": "𝗨",
    "V": "𝗩",
    "W": "𝗪",
    "X": "𝗫",
    "Y": "𝗬",
    "Z": "𝗭",
}

RELEVANT_HASHTAGS = [
    "FutureOfTech",
    "TechNews",
    "SoftwareDevelopment",
    "Innovation",
    "TechUpdate",
    "TechTrends",
    "TechInsights",
    "AI",
    "FullStack",
    "SoftwareEngineer",
    "Coding",
    "BigData",
    "Cybersecurity",
    "DataScience",
    "DevOps",
]

# lines = FUN_FACTS.strip().split("\n")  # Split by line breaks
# tips_dict = {line.split(": ")[0]: line.split(": ")[1] for line in lines}

# print(tips_dict)

# import json
# with open('fun_facts_data.json', 'w') as file:
#     json.dump(tips_dict, file, indent=4)
