# Generated by Django 4.2.6 on 2023-10-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("linkedin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkedinpost",
            name="linkedin_post_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
