# Generated by Django 4.2.6 on 2023-10-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.TextField(unique=True),
        ),
    ]
