# Generated by Django 4.2.6 on 2023-12-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_authserviceconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="authserviceconfiguration",
            name="meta",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="authserviceconfiguration",
            name="name",
            field=models.CharField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
