# Generated by Django 4.2.6 on 2023-12-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("markdown", models.TextField()),
                ("tweet_id", models.CharField(blank=True, max_length=255)),
                ("is_send", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
